application: allbuttonspressed
version: 1
runtime: python
api_version: 1

default_expiration: '365d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: common-apps/djangoappengine/deferred/handler.py
  login: admin

- url: /blank.html
  static_files: blank.html
  upload: blank.html

- url: /media/admin
  static_dir: common-apps/django/contrib/admin/media

- url: /media
  static_dir: media

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: optional

- url: /.*
  script: common-apps/djangoappengine/main/main.py
