application: allbuttonspressed
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /blank.html
  static_files: blank.html
  upload: blank.html

- url: /media/tweet-flare.xml
  static_files: static/tweet-flare.xml
  upload: static/tweet-flare.xml
  expiration: '0'

- url: /media/admin
  static_dir: django/contrib/admin/media/
  expiration: '0'

- url: /media
  static_dir: _generated_media/
  expiration: '365d'

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: optional
  expiration: '0'

- url: /.*
  script: djangoappengine/main/main.py
